apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: dGVjaHNhbG9uaWtpMTIz  # base64 encoded 'techsaloniki123'
  MYSQL_DATABASE: dGVjaHNhbG9uaWtp  # base64 encoded 'techsaloniki'
  MYSQL_USER: dXNlcg==  # base64 encoded 'user'
  MYSQL_PASSWORD: cGFzc3dvcmQxMjM=  # base64 encoded 'password123' 